package GUI;

import Control.Control;
import GoOrderDTO.ProductoDTO;
import GoOrderDTO.ProductoSeleccionadoDTO;
import Pattern.BotonRedondeado;
import Pattern.IngresarImagen;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.example.NegocioException;

/**
 * Esta clase representa la pantalla de detalle de un producto individual.
 * Aquí el usuario puede ver la foto grande, leer la descripción completa,
 * ver el precio y decidir si quiere añadir ese producto a su carrito de compras.
 *
 * @author Alex García Trejo
 */
public class DescripcionProductoFORM extends javax.swing.JFrame {

    private final Control control;
    private Color colorIluminado;
    private Color colorOriginal;
    private ProductoSeleccionadoDTO producto;
    private ProductoDTO productoDescripcion;

    /**
     * Constructor de la pantalla de descripción.
     * Recibe los datos del producto que el usuario eligió en el catálogo y prepara
     * un objeto "ProductoSeleccionadoDTO" por si el usuario decide agregarlo al carrito.
     *
     * @param control El objeto principal que maneja los datos y cambios de pantalla.
     * @param productoDescripcion Los datos completos (nombre, foto, precio, detalle) del producto a mostrar.
     */
    public DescripcionProductoFORM(Control control, ProductoDTO productoDescripcion) {
        this.control = control;
        this.productoDescripcion = productoDescripcion;
        initComponents();

        // Preparamos el producto con cantidad "1" por si el usuario le da click a añadir
        this.producto = new ProductoSeleccionadoDTO(
                productoDescripcion.getNombre(),
                1,
                productoDescripcion.getPrecio(),
                productoDescripcion.getPrecio(),
                productoDescripcion
        );
        setLocationRelativeTo(null);
        informacionProducto();
    }

    /**
     * Toma los datos del producto (nombre, descripción, precio y foto)
     * y los coloca en las etiquetas correspondientes de la interfaz gráfica
     * para que el usuario pueda verlos.
     */
    private void informacionProducto() {
        lbNombre.setText(" " + productoDescripcion.getNombre());
        lbDescripcion.setText(productoDescripcion.getDescripcion());
        lbPrecio.setText("$" + productoDescripcion.getPrecio());
        IngresarImagen.ingresarImagen(lbImagen, productoDescripcion.getImagen(), 388, 351);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbImagen = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new BotonRedondeado();
        lbPrecio = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        btnRegresar = new BotonRedondeado();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 236, 80)));

        lbDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbDescripcion.setForeground(new java.awt.Color(0, 236, 80));
        lbDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 236, 80)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 150));
        jLabel1.setText("Descripción producto");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 255, 150));
        btnAgregar.setText("Añadir al carrito");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.setFocusPainted(false);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lbPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPrecio.setForeground(new java.awt.Color(0, 236, 80));
        lbPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 236, 80)));

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 236, 80));
        lbNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 236, 80)));

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 255, 150));
        btnRegresar.setText("←");
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnAgregar)
                                                        .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel1)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(lbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cambia el color del botón "Añadir al carrito" a un verde brillante
     * cuando el usuario pasa el ratón por encima.
     */
    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        colorIluminado = new Color(51, 136, 20);
        btnAgregar.setBackground(colorIluminado);
    }//GEN-LAST:event_btnAgregarMouseEntered

    /**
     * Regresa el color del botón "Añadir al carrito" a su tono original
     * cuando el usuario quita el ratón de encima.
     */
    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        colorOriginal = new Color(35, 35, 35);
        btnAgregar.setBackground(colorOriginal);
    }//GEN-LAST:event_btnAgregarMouseExited

    /**
     * Acción que ocurre al presionar el botón "Añadir al carrito".
     * Intenta guardar el producto en el carrito del usuario. Si tiene éxito,
     * muestra un mensaje de confirmación y regresa al catálogo principal.
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            control.agregarProducto(producto);
            JOptionPane.showMessageDialog(this, "Producto añadido al carrito exitosamente.");
            control.mostrarCatalogoProductos();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar producto: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Acción que ocurre al presionar el botón de regresar (la flecha).
     * Simplemente le avisa al controlador que debe volver a mostrar la pantalla
     * del catálogo de productos.
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        control.mostrarCatalogoProductos();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * Cambia el color del botón de regresar a un verde brillante
     * cuando el usuario pasa el ratón por encima.
     */
    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        colorIluminado = new Color(51, 136, 20);
        btnRegresar.setBackground(colorIluminado);
    }//GEN-LAST:event_btnRegresarMouseEntered

    /**
     * Regresa el color del botón de regresar a su tono original
     * cuando el usuario quita el ratón de encima.
     */
    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        colorOriginal = new Color(35, 35, 35);
        btnRegresar.setBackground(colorOriginal);
    }//GEN-LAST:event_btnRegresarMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPrecio;
    // End of variables declaration//GEN-END:variables
}